services:
  app:
    volumes:
      - ./:/app
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    command: flask run --host=0.0.0.0 --port=5000 --debug
    ports:
      - "5000:5000"
