#!/usr/bin/env bash
#
# FlightDeck DG Hub — full initial server setup.
#
# Run this ONCE on a fresh Linux host (e.g. lab10.ifalabs.org), from the
# repository root. It is idempotent: re-running it is safe.
#
#   chmod +x scripts/server-setup.sh
#   ./scripts/server-setup.sh
#
# It will:
#   1. install Docker Engine + compose plugin (if missing)
#   2. create a .env with freshly generated secrets (if missing)
#   3. provision TLS certificates (self-signed by default; Let's Encrypt opt-in)
#   4. start the stack (nginx + gunicorn/Flask + MariaDB) via Docker Compose
#   5. create the database schema and the admin user
#   6. run a smoke test
#
# Configuration (override by exporting before running, e.g. `TLS_MODE=letsencrypt ./scripts/server-setup.sh`):
#
#   DOMAIN              public domain/host          (default: lab10.ifalabs.org)
#   TLS_MODE            http | selfsigned | letsencrypt   (default: selfsigned)
#   LETSENCRYPT_EMAIL   email for Let's Encrypt     (default: admin@ifalabs.org)
#   ADMIN_PASSWORD      initial admin password      (default: generated)
#
# NOTE on Let's Encrypt: it requires that DOMAIN already resolves to THIS host
# (A record) and that inbound tcp:80 is reachable from the public internet.
# As of setup, `discgolf.ifalabs.org` had NO DNS record — create one pointing
# to this VM's IP first, then run with DOMAIN=discgolf.ifalabs.org TLS_MODE=letsencrypt.
#
set -euo pipefail

DOMAIN="${DOMAIN:-lab10.ifalabs.org}"
TLS_MODE="${TLS_MODE:-selfsigned}"
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:-admin@ifalabs.org}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"

if [[ ! -f docker-compose.yml ]]; then
  echo "ERROR: run this from the repository root (docker-compose.yml not found)." >&2
  exit 1
fi

log() { printf '\n\033[1;34m>> %s\033[0m\n' "$*"; }

# --- 1. Docker -------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine + compose plugin ..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER" || true
  echo "   (you may need to log out/in for rootless docker; this run uses sudo)"
fi

# Use sudo for docker only if the current user can't reach the daemon socket.
if docker info >/dev/null 2>&1; then
  DOCKER="docker"
else
  DOCKER="sudo docker"
fi

# --- 2. Compose override selection ----------------------------------------
case "$TLS_MODE" in
  http)        OVERRIDE="docker-compose.prod.yml" ;;
  selfsigned)  OVERRIDE="docker-compose.tls.yml" ;;
  letsencrypt) OVERRIDE="docker-compose.tls.yml" ;;
  *) echo "ERROR: invalid TLS_MODE '$TLS_MODE' (use http|selfsigned|letsencrypt)" >&2; exit 1 ;;
esac
DC="$DOCKER compose -f docker-compose.yml -f $OVERRIDE"

# --- 3. .env ---------------------------------------------------------------
if [[ ! -f .env ]]; then
  log "Generating .env with fresh secrets ..."
  SECRET_KEY="$(openssl rand -hex 32)"
  DB_PASSWORD="$(openssl rand -hex 16)"
  DB_ROOT_PASSWORD="$(openssl rand -hex 16)"
  [[ -z "$ADMIN_PASSWORD" ]] && ADMIN_PASSWORD="$(openssl rand -hex 12)"
  COOKIE_SECURE=0; [[ "$TLS_MODE" != "http" ]] && COOKIE_SECURE=1

  cat > .env <<EOF
# Generated by scripts/server-setup.sh — do NOT commit this file.
SECRET_KEY=${SECRET_KEY}
FLASK_APP=run.py
DATABASE_URL=mysql+pymysql://flightdeck:${DB_PASSWORD}@db:3306/flightdeck
COOKIE_SECURE=${COOKIE_SECURE}
BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}

DOMAIN=${DOMAIN}
ALT_DOMAIN=${DOMAIN}
CERT_NAME=${DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

MARIADB_DATABASE=flightdeck
MARIADB_USER=flightdeck
MARIADB_PASSWORD=${DB_PASSWORD}
MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
EOF
  echo "   .env created. Admin password: ${ADMIN_PASSWORD}"
  echo "   >>> SAVE THIS PASSWORD — it is also stored in .env <<<"
else
  log ".env already exists — keeping it."
fi

# --- 4. TLS certificates ---------------------------------------------------
if [[ "$TLS_MODE" == "selfsigned" ]]; then
  mkdir -p certs
  if [[ ! -f certs/privkey.pem || ! -f certs/fullchain.pem ]]; then
    log "Generating self-signed certificate for ${DOMAIN} ..."
    openssl req -x509 -newkey rsa:4096 -days 365 -nodes \
      -keyout certs/privkey.pem -out certs/fullchain.pem \
      -subj "/CN=${DOMAIN}" -addext "subjectAltName=DNS:${DOMAIN}"
  else
    echo "   certs already present — keeping them."
  fi
elif [[ "$TLS_MODE" == "letsencrypt" ]]; then
  log "Requesting Let's Encrypt certificate for ${DOMAIN} (standalone, needs port 80 free + public DNS) ..."
  mkdir -p certbot/conf certbot/www certs
  $DC down >/dev/null 2>&1 || true   # free port 80
  $DOCKER run --rm -p 80:80 \
    -v "$PWD/certbot/conf:/etc/letsencrypt" \
    -v "$PWD/certbot/www:/var/www/certbot" \
    certbot/certbot certonly --standalone \
    -d "$DOMAIN" --email "$LETSENCRYPT_EMAIL" --agree-tos --no-eff-email -n
  cp -L "certbot/conf/live/${DOMAIN}/fullchain.pem" certs/fullchain.pem
  cp -L "certbot/conf/live/${DOMAIN}/privkey.pem"  certs/privkey.pem
  echo "   certificate installed into ./certs"
fi

# --- 5. Start the stack ----------------------------------------------------
log "Building and starting containers (TLS_MODE=${TLS_MODE}) ..."
$DC up -d --build

log "Waiting for the database ..."
for _ in $(seq 1 30); do
  if $DC exec -T db sh -c 'mariadb-admin ping -h localhost -p"$MARIADB_ROOT_PASSWORD" --silent' >/dev/null 2>&1; then
    echo "   database is up."; break
  fi
  sleep 2
done

log "Creating database schema ..."
$DC exec -T app flask init-db

log "Creating admin user ..."
$DC exec -T app flask create-admin || true

# --- 6. Smoke test ---------------------------------------------------------
log "Smoke test ..."
$DC ps
SCHEME="https"; [[ "$TLS_MODE" == "http" ]] && SCHEME="http"
echo "   curl -k ${SCHEME}://${DOMAIN}/api/v1/health"
curl -k -fsS "${SCHEME}://${DOMAIN}/api/v1/health" || echo "   (health check failed — check firewall / DNS / logs)"
echo

log "Done."
echo "Web UI: ${SCHEME}://${DOMAIN}/"
echo "API:    ${SCHEME}://${DOMAIN}/api/v1/health"
[[ "$TLS_MODE" == "selfsigned" ]] && echo "NOTE: self-signed cert — browsers show a warning. Use TLS_MODE=letsencrypt for a trusted cert once DNS is set."
